/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author serganimon
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegistrarUsuario = new javax.swing.JButton();
        RegistrarCliente = new javax.swing.JButton();
        RegistrarProveedor = new javax.swing.JButton();
        RegistrarRepuesto = new javax.swing.JButton();
        RegistrarVehiculo = new javax.swing.JButton();
        RegistrarUsuario5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrarUsuario.setText("REGISTRAR USUARIOS");
        RegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 180, 40));

        RegistrarCliente.setText("REGISTRAR CLIENTES");
        RegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 180, 40));

        RegistrarProveedor.setText("REGISTRAR PROVEEDOR");
        RegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 180, 40));

        RegistrarRepuesto.setText("REGISTRAR REPUESTO");
        RegistrarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarRepuestoActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 180, 40));

        RegistrarVehiculo.setText("REGISTRAR VEHICULO");
        RegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 180, 40));

        RegistrarUsuario5.setText("REGISTRAR USUARIOS");
        RegistrarUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarUsuario5ActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 180, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CarMotors");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
      private void RegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarUsuarioActionPerformed
            
      }//GEN-LAST:event_RegistrarUsuarioActionPerformed

      private void RegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarClienteActionPerformed
         RegistroCliente cliente = new RegistroCliente();
         cliente.sethome(this);
         cliente.setVisible(true);
         this.setVisible(false);
      }//GEN-LAST:event_RegistrarClienteActionPerformed

      private void RegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProveedorActionPerformed
            ProveedorCompras proveedor= new ProveedorCompras();
            proveedor.sethome(this);
            proveedor.setVisible(true);
            this.setVisible(false);
      }//GEN-LAST:event_RegistrarProveedorActionPerformed

      private void RegistrarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarRepuestoActionPerformed
            registro_repuesto repuesto = new registro_repuesto();
           repuesto.sethome(this);
            repuesto.setVisible(true);
            this.setVisible(false);
      }//GEN-LAST:event_RegistrarRepuestoActionPerformed

      private void RegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarVehiculoActionPerformed
            RegistroVehiculo vehiculo = new RegistroVehiculo();
            vehiculo.sethome(this);
            vehiculo.setVisible(true);
            this.setVisible(false);
      }//GEN-LAST:event_RegistrarVehiculoActionPerformed

      private void RegistrarUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarUsuario5ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_RegistrarUsuario5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
              new VistaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrarCliente;
    private javax.swing.JButton RegistrarProveedor;
    private javax.swing.JButton RegistrarRepuesto;
    private javax.swing.JButton RegistrarUsuario;
    private javax.swing.JButton RegistrarUsuario5;
    private javax.swing.JButton RegistrarVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
